services:
  # 1. REVERSE PROXY
  web-server:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend-net
    depends_on:
      - frontend
      - backend

  # 2. FRONTEND
  frontend:
    build:
      context: frontend
      target: build
    container_name: react-frontend
    networks:
      - frontend-net

  # 3. BACKEND
  backend:
    build: backend
    container_name: java-backend
    restart: always
    secrets:
      - db-password
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=example
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - frontend-net
      - backend-net
    depends_on:
      db:
        condition: service_healthy

  # 4. DATABASE
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 5

volumes:
  db-data: {}

secrets:
  db-password:
    file: db/password.txt

networks:
  frontend-net:
  backend-net: